### ISSUE TITLE
macOS fails, warns about awk

### ISSUE THREAD

**Issue by marmalodak** [lemnos/theme.sh#2]
./theme.sh -i

gives me an error message in the right pane:

    awk: invalid -v option

I can work around this with:

    brew install gawk

**Comment by lemnos** [comment]
Thanks for reporting this. It looks like the OSX version of awk requires a v after space. I believe it should work now (though I can't test it).

**Comment by marmalodak** [comment]
I found awk -v in three places, putting a space after the v seems to have fixed it.

**Comment by lemnos** [comment]
Yup, it should be fixed in the latest commit.
