### ISSUE TITLE
tmux true colour support check

### ISSUE THREAD

**Issue by luisdavim** [lemnos/theme.sh#20]
My tmux setup supports true colour:
![image](https://user-images.githubusercontent.com/173006/143862462-408b50bd-93af-4146-83dc-c5b32b666cef.png)

But the output of:

```console
$ tmux display-message -p '#{client_termfeatures}'
bpaste,ccolour,clipboard,cstyle,focus,RGB,title
```

Is not what this script expects.

I do have:

```sh
set -as terminal-features ",*256col*:RGB"
set -g default-terminal "tmux-256color"
```

So, when I try to run this script, I get:

```
This does not appear to be a truecolor terminal, try -i2 instead or set COLORTERM if your terminal has truecolor support.
```

Any idea of why I might be missing?

**Comment by lemnos** [comment]
I believe tmux populates `client_termfeatures` based on terminfo entries. For whatever reason your terminal doesn't seem to have truecolor support listed in your terminfo database. I assume people that have explicitly set their `TERM` environment variable to `tmux-256color` know that the parent terminal has truecolor support so I have modified the script to assume that is the case in its presence. The latest commit should produce the behaviour you expect.

**Comment by diegodorado** [comment]
I am facing the same issue
