### ISSUE TITLE
License and credits

### ISSUE THREAD

**Issue by mbadolato** [lemnos/theme.sh#21]
If you're going to be using the themes originally cultivated by me in my https://github.com/mbadolato/iTerm2-Color-Schemes repository, please make sure that you're including the copy of the MIT license, and the credits for each of the authors of the themes that are in that repository. A link back to the original repository would be appreciated, as well

Thanks
mark

**Comment by lemnos** [comment]
The themes were scraped from numerous sources and added by various contributors. It is likely your repository is among them, though in truth I don't remember explicitly scraping it. I have added a link to your repo as requested in the README. Thanks for your contribution (directly or indirectly). Feel free to reciprocate if you wish to include any themes you find here :).

**Comment by mbadolato** [comment]
Thank you! True they could have been scrapped from other places. I do know some of the themes in yours are ones I created directly, and quite a few are from the collection. I have a full credits list in my Readme, and I'm sure the authors of the themes would appreciate you including those too 😄
