### ISSUE TITLE
Add Gihub themes

### ISSUE THREAD

**Issue by luisdavim** [lemnos/theme.sh#26]
Just came across these https://github.com/projekt0n/github-nvim-theme/tree/main/extras I think they would be a nice addition to the collection.

**Comment by lemnos** [comment]
Done. Feel free to submit a PR next time, it should be a simple matter of cloning the repo and copying the kitty files into the themes folder of this project with the appropriate names (and running make).

**Comment by luisdavim** [comment]
Awesome, I'll do that the next time, thanks 👍
