### ISSUE TITLE
awk problem on chromeOS

### ISSUE THREAD

**Issue by ysr23** [lemnos/theme.sh#5]
```
$ awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
```

```
$ theme.sh/theme.sh -l
awk: line 24: illegal reference to array mru
```

I'm having a problem with -i as well but am trying to find out a bit more about truecolor on the chromeos terminal app before creating that ticket

**Comment by lemnos** [comment]
It looks like mawk doesn't implement 'length' on arrays. This should be patched now. Please confirm :).

**Comment by ysr23** [comment]
perfect, ty.
