### ISSUE TITLE
Doesn't work in tmux

### ISSUE THREAD

**Issue by faxm0dem** [lemnos/theme.sh#51]
Hi,

I just upgraded my Debian from 11 to 12 and noticed theme.sh doesn't work anymore in my setup.
Is this something which is being worked on ?

Cheers !

**Comment by jpasquier** [comment]
Hi,

Try to add

```
set-option -g allow-passthrough on
```

in your tmux configuration.

It worked for me

Best

**Comment by faxm0dem** [comment]
Thanks very much, that worked !
