### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by pjvds** [lemnos/theme.sh#6]
To make theme.sh packagable for package systems like Snap, AUR, etc. releases should be tagged. Preferable with semver versioning, so you can communicate breaking changes.

**Comment by lemnos** [comment]
Done :).

**Comment by pjvds** [comment]
Great! I've create an [AUR package](https://aur.archlinux.org/packages/theme.sh) for Arch linux users and will keep this up to date whenever you create a new release.

Thanks for the awesome work
