### ISSUE TITLE
kiTTY for Windows also supported?

### ISSUE THREAD

**Issue by guidol70** [lemnos/theme.sh#8]
As supported terminal also kiTTY is listed on your read.me-page

I did try the Windows-version KiTTY  074.3.1 @ 06/11/2020-17:31:06(GMT) while connecting via SSH to a device running armbian.
I installed fzf to the armbian device, but while scrolling the interactive mode (theme.sh -i2) the colors doenst change
and also using the sampe "theme.sh nord" cant change the color inside the terminal.

Is there anything else what I can try to use your script in my terminal?

**Comment by lemnos** [comment]
I was referring to this kitty: https://github.com/kovidgoyal/kitty. A [skim](https://github.com/cyd01/KiTTY/blob/master/0.74_My_PuTTY/terminal.c#L2885) through the source of the project you refer to would suggest that OSC 11 is not implemented your best bet is to lobby the devs to add it :(. I have updated the readme to avoid future confusion. Thanks for bringing this to my attention.
